# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CUP_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CUP_Project

  target 'CUP_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CUP_ProjectUITests' do
    # Pods for testing
  end
  
  pod 'Cosmos'
  pod 'TinyConstraints'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 4.0'

end
